---
- name: Install configuration
  vars:
    _: "{{ RS_COLLECTOR_DEFAULTS | combine(_rs_collector_ng | default({})) }}"
  template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
    mode: 0600
    owner: root
    group: root
  with_items:
    - "etc/rs-collector-ng.conf"
